### ISSUE TITLE
imap-cli-status and imap-cli-list are failing

### ISSUE THREAD

**Issue by ghost** [Gentux/imap-cli#13]
I just installed imap-cli from git like it's shown in the documentation. I have the following configuration:
```
[johrpan@trabant email]$ cat johrpan.conf 
[imap]
hostname = imap.openmailbox.org
username = johrpan@openmailbox.org
password = secret
ssl = True
```
Invoking the `imap-cli-status` command gives the following error:
```
[johrpan@trabant email]$ imap-cli-status -v -c johrpan.conf 
DEBUG:config:Reading configuration file '/home/johrpan/email/johrpan.conf'
DEBUG:config:Reading configuration file '/home/johrpan/email/johrpan.conf'
DEBUG:imap-cli:Connecting with SSL on imap.openmailbox.org
Traceback (most recent call last):
  File "/home/johrpan/.local/bin/imap-cli-status", line 11, in <module>
    load_entry_point('Imap-CLI==0.6', 'console_scripts', 'imap-cli-status')()
  File "/home/johrpan/.local/lib/python3.5/site-packages/Imap_CLI-0.6-py3.5.egg/imap_cli/summary.py", line 59, in main
    key=lambda obj: obj['directory']):
  File "/home/johrpan/.local/lib/python3.5/site-packages/Imap_CLI-0.6-py3.5.egg/imap_cli/__init__.py", line 124, in status
    for directory_info in list_dir(imap_account):
  File "/home/johrpan/.local/lib/python3.5/site-packages/Imap_CLI-0.6-py3.5.egg/imap_cli/__init__.py", line 91, in list_dir
    datum_match = LIST_DIR_RE.match(datum)
TypeError: cannot use a string pattern on a bytes-like object
```
Likewise, imap-cli-list does that:
```
[johrpan@trabant email]$ imap-cli-list -v -c johrpan.conf 
DEBUG:config:Reading configuration file '/home/johrpan/email/johrpan.conf'
DEBUG:config:Reading configuration file '/home/johrpan/email/johrpan.conf'
DEBUG:imap-cli:Connecting with SSL on imap.openmailbox.org
Traceback (most recent call last):
  File "/home/johrpan/.local/bin/imap-cli-list", line 11, in <module>
    load_entry_point('Imap-CLI==0.6', 'console_scripts', 'imap-cli-list')()
  File "/home/johrpan/.local/lib/python3.5/site-packages/Imap_CLI-0.6-py3.5.egg/imap_cli/list_mail.py", line 80, in main
    limit=limit):
  File "/home/johrpan/.local/lib/python3.5/site-packages/Imap_CLI-0.6-py3.5.egg/imap_cli/search.py", line 271, in fetch_mails_info
    ['BODY.PEEK[HEADER]', 'FLAGS', 'UID'])
  File "/home/johrpan/.local/lib/python3.5/site-packages/Imap_CLI-0.6-py3.5.egg/imap_cli/fetch.py", line 112, in fetch
    request_message_set, request_message_parts)
  File "/usr/lib/python3.5/imaplib.py", line 863, in uid
    typ, dat = self._simple_command(name, command, *args)
  File "/usr/lib/python3.5/imaplib.py", line 1180, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.5/imaplib.py", line 1011, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: UID command error: BAD [b'Error in IMAP command UID FETCH: Invalid uidset (0.000 + 0.000 secs).']
```
I don't know whether this is really a bug, because - as I said - I just installed imap-cli. Maybe I just got something wrong. Any help would be great!

**Comment by Gentux** [comment]
Hi, thanks for submitting this issue.
Should be fix by recent pull requests.

I'll release a new version to propagate new fixes
